id = "csound"
name = "Csound Zed Support"
version = "1.0.0"
schema_version = 1
authors = ["Pasquale Mainolfi <mnlpql@gmail.com>"]
description = "tree-sitter-csound grammar"
repository = "https://github.com/PasqualeMainolfi/csound-zed"


[grammars.csound]
repository = "https://github.com/PasqualeMainolfi/tree-sitter-csound"
rev = "c752934bbd84adc3abea1ae56f2b15fe813a4a61"

[language_servers.csound-lsp]
name = "Csound"
languages = ["Csound"]
