id = "csound"
name = "Csound Zed Support"
version = "1.0.0"
schema_version = 1
authors = ["Pasquale Mainolfi <mnlpql@gmail.com>"]
description = "tree-sitter-csound grammar"
repository = "https://github.com/PasqualeMainolfi/csound-zed"


[grammars.csound]
repository = "https://github.com/PasqualeMainolfi/tree-sitter-csound"
rev = "15fc1dd71e8d7d4ece60a85dd13dd6f4ff3f5010"

[language_servers.csound-lsp]
name = "Csound"
languages = ["Csound"]
