id = "csound"
name = "CSound Zed Support"
version = "0.0.1"
schema_version = 1
authors = ["Pasquale Mainolfi <mnlpql@gmail.com>"]
description = "tree-sitter-csound grammar"
repository = "https://github.com/your-name/my-zed-extension"
snippets = "grammars/csound/snippets/snippets.json"


[grammars.csound]
repository = "https://github.com/PasqualeMainolfi/tree-sitter-csound"
rev = "71a26401301376a556a70cd2f8ac669c31f01ff7"
