id = "csound"
name = "CSound Zed Support"
version = "0.1.5"
schema_version = 1
authors = ["Pasquale Mainolfi <mnlpql@gmail.com>"]
description = "tree-sitter-csound grammar"
repository = "https://github.com/PasqualeMainolfi/csound-zed"


[grammars.csound]
repository = "https://github.com/PasqualeMainolfi/tree-sitter-csound"
rev = "abc160026856c12d68ba9b912d9e1f4247b637eb"

[language_servers.csound-lsp]
name = "CSound"
languages = ["CSound"]
