id = "csound"
name = "CSound Zed Support"
version = "0.0.2"
schema_version = 1
authors = ["Pasquale Mainolfi <mnlpql@gmail.com>"]
description = "tree-sitter-csound grammar"
repository = "https://github.com/PasqualeMainolfi/csound-zed"
snippets = "snippets.json"


[grammars.csound]
repository = "https://github.com/PasqualeMainolfi/tree-sitter-csound"
rev = "99fbd3b2d42abe2e75142212a19b2888a3fb4551"
