id = "csound"
name = "CSound Zed Support"
version = "0.1.7"
schema_version = 1
authors = ["Pasquale Mainolfi <mnlpql@gmail.com>"]
description = "tree-sitter-csound grammar"
repository = "https://github.com/PasqualeMainolfi/csound-zed"


[grammars.csound]
repository = "https://github.com/PasqualeMainolfi/tree-sitter-csound"
rev = "4a51b1823f45b6bb425a0a701017370a6d2c8069"

[language_servers.csound-lsp]
name = "CSound"
languages = ["CSound"]
