id = "csound"
name = "CSound Zed Support"
version = "0.1.5"
schema_version = 1
authors = ["Pasquale Mainolfi <mnlpql@gmail.com>"]
description = "tree-sitter-csound grammar"
repository = "https://github.com/PasqualeMainolfi/csound-zed"


[grammars.csound]
repository = "https://github.com/PasqualeMainolfi/tree-sitter-csound"
rev = "01701ae3d94f697349e2a60775cb8cb4e5d1bae3"

[language_servers.csound-lsp]
name = "CSound"
languages = ["CSound"]
